export const PRODUCT_CATEGORIES = [
  '220V 1 Phass ',
  '220V 3 Phass ',
  'AC BRAKER CNC  ',
  'AC DRIVE',
  'Amp meter',
  'BATTERY',
  'BLDC',
  'BLDC SOLAR PUMP',
  'BRAKER CNC  500Vdc',
  'BRAKING RESISTOR',
  'CAPACITOR',
  'CAPACITOR BOARD',
  'Control Board',
  'DC BRAKER CNC ',
  'EV CHARGER',
  'External Keypad',
  'FAN',
  'FAN  POWTRAN',
  'FUSE CNC',
  'HYBID INVERTER ',
  'HYBRID AC/DC SOLAR',
  'Horizontal Multistage PumpsHT',
  'INVERTER',
  'INVERTER ',
  'INVERTER  POWTRAN 220V',
  'INVERTER  POWTRAN 380V',
  'INVERTER  SAJ ',
  'INVERTER VEICHI AC01 220V',
  'INVERTER VEICHI AC10 380V',
  'INVERTER VEICHI AC300 380V',
  'INVERTER VEICHI AC310 220V',
  'INVERTER VEICHI AC310 380V',
  'IOT',
  'Keypad',
  'MAGNETIC MITSUBISHI',
  'MC4 Connector',
  'MCB ABB S202M',
  'MCB ABB S203M',
  'MCB SHINOHAWA',
  'MICRO INVERTER',
  'MOT',
  'MULT VERT ELECTRIC PUMP',
  'Other',
  'PILOT LIGHT',
  'PUM-Pump',
  'Power Board',
  'Pv Optimizer ',
  'RELAY /SOCKET',
  'Reactor/Transformer',
  'Relay Expension ',
  'SELECTOR SW  ',
  'SELECTOR SWITCHES',
  'SELF PRIMING CLEAN WATER PUMP ',
  'SERVO DRIVE',
  'SOFT STARTER VEICHI',
  'SOFT STARTERPOWTRAN',
  'SOLAR INVERTER ',
  'SOLAR INVERTER  POWTRAN 380V',
  'SOLAR INVERTER  SAKO/ Sununo ',
  'SOLAR INVERTER TERA SI21 220V',
  'SOLAR INVERTER TERA SI21 380V',
  'SOLAR INVERTER TERA SI22 220V',
  'SOLAR INVERTER VEICHI  SI23 380V',
  'SOLAR INVERTER VEICHI SI23110V',
  'SOLAR INVERTER VEICHI SI23220V',
  'SOLAR INVERTER VEICHI SI30 220V',
  'SOLAR INVERTER VEICHI SI30 380V',
  'SOLAR PUMP',
  'SOLAR PV',
  'SOLAR ROOF',
  ' SUNWAY ',
  'SUBMERSIBLE PUMP',
  'SURGE PROTECTION CNC',
  'Solar Street Light',
  'Transformer',
  'Water meter',
  ' water meter',
  'smart meter sunway',
  'solar inverter',
  'volt meter',
  'กำลังไฟ 110V',
  'กำลังไฟ 220V',
  'กำลังไฟ 380V',
  'ตู้ผลิตเสร็จแล้ว (สต๊อก) ',
  'ตู้ผลิตเสร็จแล้ว รอส่ง',
  'ตู้เปล่า',
  'อื่นๆ',
  'แผงโซลาร์เซลล์ ',
  'แผงโซลาร์เซลล์ (Solar Panel)',
];
